import type { GuideContent } from "./types";

/**
 * 프로토타입용 가상 환자 안내 콘텐츠입니다.
 * 구체적인 수치(금식 시간, 복용법 등)는 예시이며, 실제 서비스 게시 전
 * 반드시 병원 공식 검토(주치의/간호부/약제부 등)를 거쳐야 합니다.
 * `needsClinicalReview: true` 항목은 임상적 판단이 포함되어 검토가
 * 특히 더 필요한 콘텐츠입니다.
 */
export const GUIDES: GuideContent[] = [
  {
    contentId: "g01",
    title: "CT 검사 전 준비",
    category: "검사",
    departments: ["영상의학과"],
    patientStages: ["ct-scheduled"],
    recommendReason: "CT 검사 예정",
    summary: "검사 전 금식과 소지품 준비 방법을 안내합니다.",
    mustCheck: "금속 장신구(목걸이, 시계, 벨트 등)는 검사 전 미리 제거해주세요.",
    beforeCare: "검사 종류에 따라 4~6시간 금식이 필요할 수 있습니다. 담당 부서 안내 시간을 확인해주세요.",
    dayOfCare: "검사 예약 시간보다 20분 일찍 영상의학과 접수처에 방문해주세요.",
    afterCare: "검사 후 특별한 제한 없이 일상생활이 가능합니다.",
    faq: [{ question: "물은 마셔도 되나요?", answer: "소량의 물은 대부분 허용되나, 담당 부서 안내를 우선 따르세요." }],
    location: "본관 2층 영상의학과",
    contact: "영상의학과 02-000-1234",
    relatedContentIds: ["g02", "g03"],
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 3,
    approvedBy: "영상의학과 간호팀",
    approvedAt: "2026-08-01",
  },
  {
    contentId: "g02",
    title: "조영제 검사 안내",
    category: "검사",
    departments: ["영상의학과"],
    patientStages: ["ct-scheduled", "mri-scheduled"],
    recommendReason: "조영제 사용 검사",
    summary: "조영제를 사용하는 검사 전 확인이 필요한 사항을 안내합니다.",
    mustCheck: "조영제 알레르기 반응 경험이 있거나 신장 기능에 이상이 있다면 반드시 검사 전 의료진에게 알려주세요.",
    beforeCare: "당뇨약(메트포르민 계열)을 복용 중이라면 사전에 담당 의료진과 복용 중단 여부를 상의해주세요.",
    afterCare: "검사 후 조영제 배출을 돕기 위해 충분한 수분 섭취를 권장합니다.",
    precautions: "검사 후 어지러움, 두드러기 등 이상 반응이 나타나면 즉시 의료진에게 알려주세요.",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    approvedBy: "영상의학과 간호팀",
    approvedAt: "2026-08-01",
  },
  {
    contentId: "g03",
    title: "영상의학과 찾아가기",
    category: "생활안내",
    departments: ["영상의학과"],
    patientStages: ["ct-scheduled", "mri-scheduled"],
    recommendReason: "검사 위치 안내",
    summary: "영상의학과 검사실 위치와 이동 경로를 안내합니다.",
    location: "본관 2층, 정문 로비에서 에스컬레이터 이용 후 좌측",
    contact: "영상의학과 접수처 02-000-1234",
    readMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
  },
  {
    contentId: "g04",
    title: "MRI 검사 안내",
    category: "검사",
    departments: ["영상의학과"],
    patientStages: ["mri-scheduled"],
    recommendReason: "MRI 검사 예정",
    summary: "MRI 검사 전 준비사항과 검사 중 유의사항을 안내합니다.",
    mustCheck: "체내 금속 삽입물(인공관절, 심장박동기 등)이 있는 경우 반드시 사전에 알려주세요.",
    beforeCare: "검사 전 화장, 금속성 액세서리는 제거해주세요.",
    dayOfCare: "검사는 부위에 따라 20~40분 정도 소요되며, 검사 중 큰 소음이 발생할 수 있습니다.",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    approvedBy: "영상의학과 간호팀",
    approvedAt: "2026-07-20",
  },
  {
    contentId: "g05",
    title: "검사 후 주의사항",
    category: "검사",
    departments: ["영상의학과", "소화기내과"],
    patientStages: ["ct-scheduled", "mri-scheduled", "gastroscopy-scheduled", "colonoscopy-scheduled"],
    recommendReason: "검사 이후 단계",
    summary: "검사 종류와 관계없이 검사 후 공통으로 확인해야 할 사항입니다.",
    precautions: "발열, 심한 복통, 출혈 등 평소와 다른 증상이 나타나면 즉시 병원에 연락하세요.",
    contact: "대표전화 02-000-0000 (야간·주말 응급실 02-000-0119)",
    readMinutes: 1,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
  },
  {
    contentId: "g06",
    title: "위내시경 검사 안내",
    category: "검사",
    departments: ["소화기내과"],
    patientStages: ["gastroscopy-scheduled"],
    recommendReason: "위내시경 검사 예정",
    summary: "위내시경 검사 절차와 진정 내시경 여부에 따른 주의사항을 안내합니다.",
    beforeCare: "검사 전 8시간 금식이 필요합니다(물 포함, 담당 부서 안내 우선).",
    dayOfCare: "진정 내시경으로 진행하는 경우, 검사 후 직접 운전은 삼가고 보호자와 동행해주세요.",
    afterCare: "검사 후 목 이물감이 있을 수 있으며 대부분 자연히 호전됩니다.",
    faq: [{ question: "혈압약은 먹어도 되나요?", answer: "소량의 물과 함께 복용 가능한 경우가 많으나, 담당 의료진 확인이 필요합니다." }],
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 3,
    approvedBy: "소화기내과 간호팀",
    approvedAt: "2026-08-10",
  },
  {
    contentId: "g07",
    title: "대장내시경 검사 안내",
    category: "검사",
    departments: ["소화기내과"],
    patientStages: ["colonoscopy-scheduled"],
    recommendReason: "대장내시경 검사 예정",
    summary: "대장내시경 검사를 위한 장 정결 준비 절차를 안내합니다.",
    mustCheck: "장 정결제는 처방받은 시간과 방법을 반드시 지켜서 복용해주세요.",
    beforeCare: "검사 전날 저녁부터 저잔사식(소화가 잘 되는 음식) 위주로 섭취하고, 처방된 장 정결제를 복용합니다.",
    dayOfCare: "검사 당일에는 물 이외의 음식 섭취를 피해주세요.",
    afterCare: "가스가 찬 느낌이 있을 수 있으며 시간이 지나면 호전됩니다.",
    readMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    approvedBy: "소화기내과 간호팀",
    approvedAt: "2026-08-10",
  },
  {
    contentId: "g08",
    title: "내시경 검사 전 금식 안내",
    category: "검사",
    departments: ["소화기내과"],
    patientStages: ["gastroscopy-scheduled", "colonoscopy-scheduled"],
    recommendReason: "검사 전 금식 필요",
    summary: "내시경 검사 전 금식 시간과 복용 중단이 필요한 약물을 안내합니다.",
    mustCheck: "항응고제(혈액을 묽게 하는 약)를 복용 중이라면 검사 전 반드시 담당 의료진과 상의해주세요.",
    beforeCare: "검사 전 최소 8시간 금식이 필요합니다.",
    readMinutes: 1,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
  },
  {
    contentId: "g09",
    title: "소화기내과 검사실 찾아가기",
    category: "생활안내",
    departments: ["소화기내과"],
    patientStages: ["gastroscopy-scheduled", "colonoscopy-scheduled"],
    recommendReason: "검사 위치 안내",
    summary: "소화기내과 내시경실 위치와 접수 방법을 안내합니다.",
    location: "별관 3층 내시경센터",
    contact: "내시경센터 02-000-2222",
    readMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
  },
  {
    contentId: "g10",
    title: "수술 전 준비",
    category: "수술",
    departments: ["외과", "정형외과"],
    patientStages: ["surgery-scheduled"],
    recommendReason: "수술 예정",
    summary: "입원 및 수술 전 준비물과 확인 사항을 안내합니다.",
    mustCheck: "복용 중인 모든 약물(건강기능식품 포함)을 입원 시 의료진에게 알려주세요.",
    beforeCare: "수술 전날 자정부터 금식이 필요하며, 세부 시간은 담당 병동 안내를 따라주세요.",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 3,
    approvedBy: "외과 병동",
    approvedAt: "2026-07-15",
  },
  {
    contentId: "g11",
    title: "수술 동의서 및 입원 절차 안내",
    category: "수술",
    departments: ["외과", "정형외과"],
    patientStages: ["surgery-scheduled"],
    recommendReason: "입원·수술 절차 안내",
    summary: "입원 수속과 수술 동의서 작성 절차를 안내합니다.",
    beforeCare: "입원 당일 원무과에서 입원 수속 후 병동으로 안내받습니다.",
    contact: "입퇴원수속센터 02-000-3333",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
  },
  {
    contentId: "g12",
    title: "수술 후 회복 안내",
    category: "수술",
    departments: ["외과", "정형외과"],
    patientStages: ["surgery-scheduled"],
    recommendReason: "수술 후 회복 단계",
    summary: "수술 직후 회복 과정에서 확인해야 할 사항을 안내합니다.",
    afterCare: "마취 회복 후 의료진 지시에 따라 단계적으로 식이를 진행합니다.",
    precautions: "심한 통증, 출혈, 고열이 있으면 즉시 담당 병동 간호사에게 알려주세요.",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    approvedBy: "외과 병동",
    approvedAt: "2026-07-15",
  },
  {
    contentId: "g13",
    title: "입원생활 안내",
    category: "입원",
    departments: ["외과", "정형외과", "순환기내과", "내과"],
    patientStages: ["surgery-scheduled", "admitted"],
    recommendReason: "입원 중 생활 안내",
    summary: "병동 생활 중 알아두면 좋은 편의시설과 면회 안내입니다.",
    beforeCare: "병동 면회 시간과 보호자 상주 규정은 병동 게시판을 확인해주세요.",
    location: "각 병동 안내데스크",
    contact: "입원 병동 대표전화 02-000-4444",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
  },
  {
    contentId: "g14",
    title: "채혈 안내",
    category: "검사",
    departments: ["내과", "순환기내과", "외과", "정형외과"],
    patientStages: ["blood-test-scheduled", "admitted"],
    recommendReason: "채혈 검사 예정",
    summary: "채혈 검사 전후 확인 사항을 안내합니다.",
    beforeCare: "검사 항목에 따라 8~12시간 금식이 필요할 수 있습니다.",
    afterCare: "채혈 부위는 5분 이상 지그시 눌러 지혈해주세요.",
    readMinutes: 1,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
  },
  {
    contentId: "g15",
    title: "퇴원 후 생활 안내",
    category: "퇴원",
    departments: ["내과", "순환기내과", "외과", "정형외과"],
    patientStages: ["discharge-scheduled"],
    recommendReason: "퇴원 예정",
    summary: "퇴원 후 일상 복귀 시 참고할 생활 수칙을 안내합니다.",
    afterCare: "무리한 활동은 피하고, 컨디션에 맞춰 점진적으로 일상생활을 재개하세요.",
    precautions: "퇴원 후 발열, 상처 부위 이상, 평소와 다른 증상이 있다면 외래 방문 전이라도 병원에 문의하세요.",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    approvedBy: "간호부",
    approvedAt: "2026-06-10",
  },
  {
    contentId: "g16",
    title: "복약 안내",
    category: "복약",
    departments: ["내과", "순환기내과", "외과", "정형외과"],
    patientStages: ["discharge-scheduled", "admitted"],
    recommendReason: "퇴원 처방 약물 복용",
    summary: "퇴원 처방약 복용 시간과 놓쳤을 때 대처법을 안내합니다.",
    mustCheck: "임의로 약 복용을 중단하거나 용량을 조절하지 마세요.",
    beforeCare: "처방받은 시간에 맞춰 규칙적으로 복용해주세요.",
    faq: [{ question: "복용을 깜빡했어요.", answer: "생각난 즉시 복용하되, 다음 복용 시간과 가까우면 한 번만 복용하세요." }],
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 3,
    approvedBy: "약제부",
    approvedAt: "2026-06-10",
  },
  {
    contentId: "g17",
    title: "외래 방문 예약 안내",
    category: "퇴원",
    departments: ["내과", "순환기내과", "외과", "정형외과"],
    patientStages: ["discharge-scheduled"],
    recommendReason: "퇴원 후 외래 예약 필요",
    summary: "퇴원 후 경과 확인을 위한 외래 방문 일정을 안내합니다.",
    contact: "외래 예약센터 02-000-5555",
    readMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
  },
  {
    contentId: "g18",
    title: "혈압 자가관리 안내",
    category: "생활안내",
    departments: ["순환기내과"],
    patientStages: ["admitted", "discharge-scheduled"],
    recommendReason: "혈압 관리 필요",
    summary: "가정에서 혈압을 측정하고 기록하는 방법을 안내합니다.",
    beforeCare: "아침·저녁 각 1회, 같은 시간대에 측정하는 습관을 들이면 좋습니다.",
    faq: [{ question: "측정값이 평소보다 많이 높아요.", answer: "안정 후 재측정해보고, 반복적으로 높다면 외래 방문 전이라도 문의해주세요." }],
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
  },
  {
    contentId: "g19",
    title: "저염식 식단 안내",
    category: "생활안내",
    departments: ["순환기내과"],
    patientStages: ["admitted", "discharge-scheduled"],
    recommendReason: "저염식 관리 필요",
    summary: "혈압 관리를 위한 저염식 식단 구성 팁을 안내합니다.",
    afterCare: "국물류 섭취를 줄이고, 조리 시 소금 대신 향신료를 활용해보세요.",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
  },
  {
    contentId: "g20",
    title: "인공관절 수술 후 재활운동 안내",
    category: "수술",
    departments: ["정형외과"],
    patientStages: ["surgery-scheduled"],
    recommendReason: "인공관절 수술 후 재활 필요",
    summary: "수술 후 단계별 재활운동 방법을 안내합니다.",
    afterCare: "의료진이 안내하는 범위 내에서 단계적으로 관절 운동 범위를 늘려갑니다.",
    precautions: "무리한 운동은 오히려 회복을 늦출 수 있으니 반드시 담당 의료진의 운동 처방을 따르세요.",
    readMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    approvedBy: "재활의학과",
    approvedAt: "2026-07-01",
  },
  {
    contentId: "g21",
    title: "상처 관리 기본 안내",
    category: "수술",
    departments: ["외과", "정형외과"],
    patientStages: ["surgery-scheduled"],
    recommendReason: "수술 부위 상처 관리",
    summary: "수술 부위 소독과 드레싱 교체 주기를 안내합니다.",
    afterCare: "드레싱은 담당 의료진이 안내한 주기에 맞춰 교체합니다.",
    precautions: "상처 부위에 발적, 진물, 열감이 있으면 감염 가능성이 있으니 즉시 병원에 문의하세요.",
    readMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
  },
  {
    contentId: "g22",
    title: "낙상 예방 안내",
    category: "입원",
    departments: ["내과", "순환기내과", "외과", "정형외과"],
    patientStages: ["admitted"],
    recommendReason: "입원 중 낙상 예방",
    summary: "입원 중 낙상을 예방하기 위한 생활 수칙을 안내합니다.",
    precautions: "어지러움이 있을 때는 침대에서 천천히 일어나고, 필요 시 호출벨로 도움을 요청하세요.",
    readMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
  },
];

export function findGuideById(contentId: string): GuideContent | undefined {
  return GUIDES.find((g) => g.contentId === contentId);
}
