import type { GuideContent } from "./types";

/**
 * 프로토타입용 Mock 콘텐츠입니다. 구체적인 수치(금식 시간, 복용법 등)는
 * 예시이며, 실제 게시 전 반드시 병원 공식 검토(주치의/간호부/약제부 등)를
 * 거쳐야 합니다. `needsClinicalReview: true` 항목은 특히 더 필요합니다.
 *
 * Phase 1에서는 환자 데이터와 연결하지 않습니다. `slug`는 환자에게
 * 전달되는 고정 URL(/c/[slug])에 쓰이며 개인정보를 포함하지 않습니다.
 */
export const GUIDES: GuideContent[] = [
  // ───────────────────── 검사 (15) ─────────────────────
  {
    contentId: "c01",
    slug: "ct-prep",
    title: "CT 검사 안내",
    category: "검사",
    subcategory: "CT",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "조영제 사용 여부에 따른 금식 시간부터 검사 당일 절차, 검사 후 주의사항까지 CT 검사 전 과정을 안내합니다.",
    importantNotice:
      "조영제를 사용하는 검사인 경우 금속 신장질환·조영제 알레르기·임신 여부·당뇨약(메트포르민 성분) 복용 여부를 검사 전 반드시 알려주셔야 합니다.",
    before:
      "조영제를 사용하는 CT는 검사 4~6시간 전부터 금식이 필요하며, 조영제를 사용하지 않는 CT(뼈·흉부 등 단순 촬영)는 별도의 금식이 필요 없는 경우가 많습니다. 검사 예약 시 안내받은 금식 시간을 확인해주세요. 임신 가능성, 조영제 알레르기 병력, 신장질환, 당뇨약 복용 여부는 예약 시 또는 검사 전 접수 시 반드시 알려주세요. 금속 장신구·보청기·틀니 등은 미리 제거해 오시면 대기 시간이 줄어듭니다.",
    during:
      "검사 전 영상의학과 접수처에 방문해 접수해주세요. 환복이 필요한 경우 검사복으로 갈아입고 대기합니다. 조영제를 사용하는 경우 팔 정맥에 주사로 주입하며, 주입 시 몸이 따뜻해지거나 입안에서 금속 맛이 느껴질 수 있는데 이는 대부분 일시적인 정상 반응입니다. 검사 자체는 10~20분 내외로 짧지만, 상황에 따라 시간이 달라질 수 있습니다.",
    after:
      "조영제를 사용한 경우 체내 배출을 돕기 위해 검사 후 충분한 수분(물) 섭취를 권장합니다. 특별한 활동 제한은 없어 검사 후 바로 일상생활이 가능합니다. 다만 검사 후 수 시간 내 두드러기, 가려움, 호흡곤란 등 지연성 알레르기 반응이 나타날 수 있으니, 증상이 있으면 즉시 영상의학과 또는 응급실로 연락해주세요. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    faq: [
      { question: "물은 마셔도 되나요?", answer: "검사 전 소량의 물은 대부분 허용되나, 조영제 사용 여부에 따라 다르므로 담당 부서 안내를 우선 따르세요." },
      { question: "조영제 부작용이 걱정돼요.", answer: "가려움·두드러기 같은 경미한 반응이 흔하지만, 호흡곤란처럼 심한 반응은 드뭅니다. 알레르기 병력이 있다면 검사 전 반드시 미리 알려주시면 예방 조치를 받을 수 있습니다." },
      { question: "임신 중인데 CT를 찍어도 되나요?", answer: "임신(가능성 포함) 사실은 예약 또는 접수 시 반드시 먼저 알려주세요. 방사선 노출을 고려해 검사 방법이 조정되거나 다른 검사로 대체될 수 있습니다." },
    ],
    location: "본관 3층 영상의학과 CT촬영실",
    contact: "영상의학과 검사예약 02-2290-8114",
    relatedContentIds: ["c10", "c14"],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-18",
  },
  {
    contentId: "c02",
    slug: "mri-prep",
    title: "MRI 검사 안내",
    category: "검사",
    subcategory: "MRI",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "조영제 사용 여부에 따른 금식 시간부터 검사 당일 절차, 검사 후 주의사항까지 MRI 검사 전 과정을 안내합니다.",
    importantNotice:
      "체내 금속 삽입물(인공관절, 심장박동기, 인공와우, 신경자극기 등)이나 문신·반영구화장이 있는 경우 반드시 사전에 알려주세요.",
    before:
      "검사 전 화장, 금속성 액세서리(귀걸이, 목걸이, 벨트 등)는 제거해주세요. 폐쇄공포감이 있다면 검사 전 미리 의료진에게 알려주시면 안정을 돕는 방법을 안내받을 수 있습니다.",
    during:
      "검사 중 소음이 발생하므로 귀마개를 착용할 수 있습니다. 조영제를 사용하는 경우 검사 전 정맥주사를 삽입합니다.",
    after:
      "조영제를 사용한 경우 배출을 돕기 위해 충분한 수분(3컵) 섭취를 권장합니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    faq: [{ question: "폐쇄공포증이 있는데 검사가 가능한가요?", answer: "사전에 알려주시면 진정제 사용이나 개방형 MRI 등 대안을 상의할 수 있습니다." }],
    location: "본관 3층 영상의학과 MRI촬영실",
    contact: "영상의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c03",
    slug: "xray-prep",
    title: "X-ray 검사 안내",
    category: "검사",
    subcategory: "X-ray",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "X-ray 촬영 시 준비사항과 소요 시간을 안내합니다.",
    before: "촬영 부위에 금속(단추, 지퍼, 액세서리)이 없도록 준비해주세요.",
    during: "촬영은 부위당 5분 이내로 짧게 진행되며, 안내에 따라 자세를 잡고 잠시 숨을 참게 됩니다.",
    after: "촬영 후 특별한 제한 없이 바로 일상생활이 가능합니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "본관 3층 영상의학과 일반촬영실",
    contact: "영상의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c04",
    slug: "ultrasound-prep",
    title: "초음파 검사 안내",
    category: "검사",
    subcategory: "초음파",
    departments: ["영상의학과", "내과"],
    patientStages: ["before-test"],
    summary: "복부·갑상선 등 초음파 검사별 준비사항을 안내합니다.",
    importantNotice: "복부 초음파는 검사 종류에 따라 금식이 필요할 수 있습니다.",
    before: "담당 부서에서 안내한 금식·수분 섭취 기준을 확인해주세요.",
    during:
      "검사 부위에 젤을 바른 뒤 탐촉자로 부위를 눌러가며 촬영하며, 통증 없이 10~20분 정도 소요됩니다. 검사 중 자세를 바꾸거나 숨을 참으라는 안내가 있을 수 있습니다.",
    after: "젤을 닦아내면 바로 일상생활이 가능하며 별도의 주의사항은 없습니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "본관 2층 영상의학과 초음파검사실",
    contact: "영상의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c05",
    slug: "gastroscopy-prep",
    title: "위내시경 검사 안내",
    category: "검사",
    subcategory: "위내시경",
    departments: ["소화기내과"],
    patientStages: ["before-test"],
    summary: "위내시경 검사 절차와 진정 내시경 여부에 따른 주의사항을 안내합니다.",
    before: "검사 전 8시간 금식이 필요합니다(물 포함, 담당 부서 안내 우선).",
    during: "진정 내시경으로 진행하는 경우, 검사 후 직접 운전은 삼가고 보호자와 동행해주세요.",
    after: "검사 후 목 이물감이 있을 수 있으며 대부분 자연히 호전됩니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    faq: [{ question: "혈압약은 먹어도 되나요?", answer: "소량의 물과 함께 복용 가능한 경우가 많으나, 담당 의료진 확인이 필요합니다." }],
    location: "서관 6층 소화기 내시경 검사실",
    contact: "소화기내과 검사예약 02-2290-8114",
    relatedContentIds: ["c07", "c46"],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-08-01",
  },
  {
    contentId: "c06",
    slug: "colonoscopy-prep",
    title: "대장내시경 검사 안내",
    category: "검사",
    subcategory: "대장내시경",
    departments: ["소화기내과"],
    patientStages: ["before-test"],
    summary: "대장내시경 검사를 위한 장 정결 준비 절차를 안내합니다.",
    importantNotice: "장 정결제는 처방받은 시간과 방법을 반드시 지켜서 복용해주세요.",
    before: "검사 전날 저녁부터 저잔사식 위주로 섭취하고, 처방된 장 정결제를 복용합니다.",
    during: "검사 당일에는 물 이외의 음식 섭취를 피해주세요.",
    after: "가스가 찬 느낌이 있을 수 있으며 시간이 지나면 호전됩니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "서관 6층 소화기 내시경 검사실",
    contact: "소화기내과 검사예약 02-2290-8114",
    relatedContentIds: ["c05", "c46"],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-08-01",
  },
  {
    contentId: "c07",
    slug: "blood-test",
    title: "채혈 및 임상검사 안내",
    category: "검사",
    subcategory: "채혈 및 임상검사",
    departments: ["진단검사의학과", "전과공통"],
    patientStages: ["before-test", "admitted"],
    summary: "채혈 검사 전후 확인 사항을 안내합니다.",
    before: "검사 항목에 따라 8~12시간 금식이 필요할 수 있습니다.",
    during:
      "채혈실 순번에 따라 이름과 등록번호를 확인한 뒤 진행하며, 검사 항목에 따라 1~3개 튜브 정도의 혈액을 채취합니다. 소요 시간은 5분 이내로 짧습니다.",
    after: "채혈 부위는 5분 이상 지그시 눌러 지혈해주세요. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "본관 3층 진단검사의학과 채혈실",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c08",
    slug: "biopsy-prep",
    title: "조직검사 안내",
    category: "검사",
    subcategory: "조직검사",
    departments: ["외과", "소화기내과"],
    patientStages: ["before-test"],
    summary: "조직검사 절차와 결과 확인까지 걸리는 기간을 안내합니다.",
    importantNotice: "항응고제(혈액을 묽게 하는 약) 복용 중이라면 검사 전 반드시 의료진과 상의해주세요.",
    before:
      "항응고제나 아스피린 계열 약물을 복용 중이라면 검사 며칠 전부터 중단이 필요할 수 있으니 사전에 반드시 담당 의료진과 상의해주세요. 검사 부위에 따라 금식이 필요할 수 있습니다.",
    during:
      "국소마취 후 바늘이나 특수 기구로 조직을 채취하며, 부위에 따라 10~30분 정도 소요됩니다. 검사 중 눌리는 느낌이나 약간의 통증이 있을 수 있습니다.",
    after: "검사 부위 통증이나 소량의 출혈이 있을 수 있으며, 조직검사 결과는 통상 5~7일 소요됩니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c09",
    slug: "pet-ct-prep",
    title: "PET-CT 검사 안내",
    category: "검사",
    subcategory: "PET-CT",
    departments: ["핵의학과"],
    patientStages: ["before-test"],
    summary: "방사성의약품을 이용한 PET-CT 검사 준비사항을 안내합니다.",
    importantNotice: "검사 전날부터 격렬한 운동을 피하고, 당일 검사 전 6시간 금식이 필요합니다.",
    before: "혈당이 높으면 검사가 지연될 수 있어, 당뇨가 있는 경우 사전에 알려주세요.",
    during: "약물 주입 후 1시간가량 안정을 취한 뒤 촬영이 진행되며, 촬영 자체는 20~30분 정도 소요됩니다.",
    after:
      "검사 후 방사성의약품 배출을 돕기 위해 충분한 수분(3컵) 섭취를 권장합니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "본관 2층 핵의학과 PET-CT/감마카메라실",
    contact: "핵의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c10",
    slug: "contrast-media",
    title: "조영제 검사 및 부작용 안내",
    category: "검사",
    subcategory: "조영제 검사 및 부작용",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "조영제를 사용하는 검사 전 확인이 필요한 사항을 안내합니다.",
    importantNotice: "조영제 알레르기 반응 경험이 있거나 신장 기능에 이상이 있다면 반드시 검사 전 의료진에게 알려주세요.",
    before: "당뇨약(메트포르민 계열) 복용 중이라면 사전에 담당 의료진과 복용 중단 여부를 상의해주세요.",
    during:
      "검사 종류에 따라 정맥주사 또는 경구로 조영제를 투여하며, 투여 시 몸이 따뜻해지거나 금속 맛이 느껴질 수 있는데 대부분 일시적인 정상 반응입니다. 이상 증상이 느껴지면 즉시 의료진에게 알려주세요.",
    after:
      "조영제 배출을 돕기 위해 충분한 수분(3컵) 섭취를 권장하며, 어지러움·두드러기 등 이상 반응 시 즉시 알려주세요. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "본관 3층 영상의학과",
    contact: "영상의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c11",
    slug: "ekg-prep",
    title: "심전도 검사 안내",
    category: "검사",
    subcategory: "심전도",
    departments: ["순환기내과"],
    patientStages: ["before-test"],
    summary: "심전도 검사 절차와 소요 시간을 안내합니다.",
    before: "검사 전 특별한 준비는 필요 없으나, 로션이나 오일 사용은 전극 부착을 방해할 수 있어 피해주세요.",
    during: "상의를 탈의하고 가슴, 팔, 다리에 전극을 부착해 5분 이내로 측정합니다.",
    after: "검사 후 특별한 제한 없이 바로 일상생활이 가능합니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "서관 5층 심전도실",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c12",
    slug: "echocardiography-prep",
    title: "심장초음파 검사 안내",
    category: "검사",
    subcategory: "심장초음파",
    departments: ["순환기내과"],
    patientStages: ["before-test"],
    summary: "심장초음파 검사 준비사항과 소요 시간을 안내합니다.",
    before: "별도의 금식 없이 진행되나, 담당 부서 안내를 우선 확인해주세요.",
    during: "검사는 30분 내외로 진행되며 왼쪽으로 누운 자세를 취하게 됩니다.",
    after:
      "검사 후 특별한 제한 없이 바로 일상생활이 가능합니다. 젤은 닦아내시면 됩니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "서관 5층 심장내과 심장초음파실",
    contact: "순환기내과 검사예약 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c13",
    slug: "nuclear-medicine-prep",
    title: "핵의학검사 안내",
    category: "검사",
    subcategory: "핵의학검사",
    departments: ["핵의학과"],
    patientStages: ["before-test"],
    summary: "뼈scan 등 핵의학검사 절차와 소요 시간을 안내합니다.",
    before: "방사성의약품 주입 후 촬영까지 대기 시간이 있을 수 있습니다.",
    during: "방사성의약품을 주사한 후 검사 종류에 따라 수십 분에서 몇 시간의 대기 시간을 거쳐 촬영을 진행합니다. 촬영 자체는 통증이 없습니다.",
    after: "검사 후 방사성의약품 배출을 돕기 위해 충분한 수분(3컵) 섭취를 권장합니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "본관 2층 핵의학과",
    contact: "핵의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c14",
    slug: "fasting-guide",
    title: "검사 전 금식 가이드",
    category: "검사",
    subcategory: "검사 전 금식 가이드",
    departments: ["전과공통"],
    patientStages: ["before-test"],
    summary: "검사 종류별 금식 기준을 한눈에 정리한 공통 안내입니다.",
    importantNotice: "검사별 금식 시간이 다르므로 반드시 담당 부서 안내를 우선 확인해주세요.",
    before:
      "일반채혈: 검사 항목에 따라 8~12시간 금식이 필요할 수 있습니다. 초음파: 검사 부위에 따라 금식이 필요할 수 있으며, 해당없는 경우도 있으니 담당 부서 안내를 확인해주세요. 내시경(위내시경): 8시간 금식이 필요합니다. 내시경(대장내시경): 전날 저잔사식과 장 정결제 복용이 필요하며, 검사 당일은 물 이외 음식 섭취를 금합니다. PET-CT: 검사 6시간 전부터 금식이 필요합니다. CT: 조영제를 사용하는 경우 검사 4~6시간 전부터 금식이 필요하며, 조영제를 사용하지 않는 단순 촬영(뼈·흉부 등)은 해당없음(금식 불필요)입니다. MRI: 해당없음(별도의 금식이 필요하지 않습니다). X-RAY: 해당없음(별도의 금식이 필요하지 않습니다).",
    phaseLabelOverride: { before: "검사 종류" },
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-08-01",
  },
  {
    contentId: "c15",
    slug: "mammography-prep",
    title: "유방촬영(맘모그래피) 검사 안내",
    category: "검사",
    subcategory: "유방촬영(맘모그래피)",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "유방촬영 검사 시 준비사항과 촬영 시 유의사항을 안내합니다.",
    before: "검사 당일 데오드란트, 파우더 사용은 피해주세요.",
    during: "압박 촬영 시 일시적으로 불편감이 있을 수 있습니다.",
    after:
      "촬영 후 일시적으로 압박 부위가 눌린 느낌이 있을 수 있으나 곧 회복됩니다. 특별한 제한 없이 바로 일상생활이 가능합니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    location: "본관 2층 영상의학과 유방촬영실",
    contact: "영상의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },

  // ───────────────────── 수술 (4) ─────────────────────
  {
    contentId: "c16",
    slug: "surgery-guide",
    title: "수술 안내",
    category: "수술",
    subcategory: "수술 전·중·후",
    departments: ["외과", "정형외과"],
    patientStages: ["before-surgery", "admitted"],
    summary: "입원 및 수술 전 준비물부터 수술 당일 절차, 수술 후 회복 과정까지 전 과정을 안내합니다.",
    importantNotice:
      "복용 중인 모든 약물(건강기능식품 포함)을 입원 시 의료진에게 알려주세요. 수술 후 심한 통증, 출혈, 고열이 있으면 즉시 담당 간호사에게 알려주세요.",
    before:
      "수술 전날 자정부터 금식이 필요하며, 세부 시간은 담당 병동 안내를 따라주세요. 복용 중인 모든 약물(건강기능식품 포함)은 입원 시 의료진에게 알려주시고, 의료진 확인 없이 임의로 복용을 중단하거나 지속하지 마세요. 수술 동의서 작성과 마취 사전 상담은 별도 안내에 따라 진행됩니다.",
    during:
      "수술 전날 병동에서 환복, 정맥주사 확보 등 수술 준비를 마친 후 수술 당일 수술 스케줄대로 수술 준비실로 이동하며, 이동 전 의료진의 최종 확인 절차를 거칩니다. 수술 진행 안내는 입원 시 등록한 보호자 번호로 문자 발송되며 수술이 끝나면 담당의가 결과를 안내합니다.",
    after:
      "마취 회복 후 의료진 지시에 따라 단계적으로 식이를 진행하며, 통증·배액관·상처 상태를 의료진이 주기적으로 확인합니다. 심한 통증, 출혈, 고열이 있으면 즉시 담당 간호사에게 알려주세요.",
    faq: [
      {
        question: "보호자는 수술 중 어디서 기다리나요?",
        answer: "입원하신 병실에서 대기하실 수 있으며, 본관 3층 응급실 대기실을 이용할 수 있습니다.",
      },
    ],
    location: "본관 5층 수술실 · 본관 3층 응급실 대기실(보호자 대기)",
    relatedContentIds: ["c19", "c22"],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c19",
    slug: "post-surgery-recovery",
    title: "수술 후 회복 관리 안내",
    category: "수술",
    subcategory: "수술 후 통증·식사·재활",
    departments: ["외과", "정형외과", "마취통증의학과", "재활의학과"],
    patientStages: ["admitted", "after-discharge"],
    summary: "수술 후 통증 조절, 단계별 식이 진행, 재활운동과 폐 합병증 예방(인스피로미터 사용법)까지 회복 전 과정을 안내합니다.",
    importantNotice:
      "통증을 참기보다 담당 의료진에게 통증 정도를 알려 적절한 조절을 받으시고, 무리한 운동은 오히려 회복을 늦출 수 있으니 반드시 담당 의료진의 운동 처방을 따르세요.",
    during:
      "수술 후 통증을 조절이 필요한 경우 언제든지 의료진에게 알려주시기 바랍니다. 자가 통증 조절 장치(PCA)를 사용하는 경우 사용법을 담당 간호사에게 안내받으며, 정해진 용량 안에서 스스로 조절할 수 있습니다.",
    after:
      "장 기능 회복 정도에 따라 의료진이 금식→유동식→일반식 순으로 식이를 단계적으로 조절합니다. 폐 합병증(폐렴, 무기폐) 예방을 위해 인스피로미터(폐활량 운동기구)를 하루 여러 차례 사용해주세요: 마우스피스를 입에 물고 천천히 최대한 깊게 들이마셔 공이나 피스톤을 목표 높이까지 끌어올린 뒤 2~3초간 유지하고 천천히 내쉽니다. 이 외에도 의료진이 안내하는 범위 내에서 단계적으로 관절 운동 범위를 늘려가며, 무리한 운동은 오히려 회복을 늦출 수 있으니 반드시 담당 의료진의 운동 처방을 따르세요. 수술 부위 관리: 드레싱은 담당 의료진이 주기에 맞춰 교체합니다. 상처 부위에 발적, 진물, 열감이 있으면 감염 가능성이 있으니 즉시 병원에 문의하세요.",
    faq: [
      {
        question: "인스피로미터는 왜 사용하나요?",
        answer:
          "수술 후 얕은 호흡이 지속되면 폐렴 등 폐 합병증 위험이 높아집니다. 인스피로미터로 깊은 호흡을 반복 연습하면 폐가 완전히 펴지는 데 도움이 되어 합병증을 예방할 수 있습니다.",
      },
    ],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c22",
    slug: "surgery-consent",
    title: "수술 동의서 및 마취 상담 안내",
    category: "수술",
    subcategory: "수술 동의서 작성 및 마취 사전 상담",
    departments: ["외과", "정형외과", "마취통증의학과"],
    patientStages: ["before-surgery"],
    summary: "수술 동의서 작성 절차와 마취 방법·위험도를 확인하는 마취 사전 상담 절차를 함께 안내합니다.",
    before:
      "수술 동의서는 집도의의 수술 설명을 들은 후 환자 본인 또는 법정대리인이 입원하신 병동(병실)에서 서명합니다. 마취 사전 상담에서는 기존 질환, 복용 약물, 마취 관련 과거력을 정확히 알려주세요.",
    location: "입원 병동(수술 동의서) · 본관 5층 마취통증의학과(마취 사전 상담)",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c24",
    slug: "procedure-before-after",
    title: "시술 전후 안내",
    category: "수술",
    subcategory: "전후 관리",
    departments: ["외과", "내과", "순환기내과", "소화기내과"],
    patientStages: ["before-surgery", "admitted"],
    summary: "수술보다 회복이 짧은 대표 시술(관상동맥조영술/스텐트 삽입술, 내시경 용종절제술, 중심정맥관/케모포트 삽입술) 전후 유의사항을 안내합니다.",
    before:
      "시술 전 공통으로 금식 여부와 항응고제(혈액을 묽게 하는 약)·아스피린 계열 약물 중단 여부를 담당 의료진과 반드시 상의해야 합니다. [관상동맥조영술/스텐트 삽입술] 시술 4~6시간 전부터 금식이 필요하며, 항응고제 복용 중이라면 사전에 중단 여부를 상의합니다. [내시경 용종절제술] 위내시경·대장내시경과 동일하게 8시간 이상 금식이 필요하며, 대장 용종절제술의 경우 장 정결제 복용이 추가로 필요합니다. [중심정맥관/케모포트 삽입술] 별도의 금식 없이 진행되는 경우가 많으나, 항응고제 복용 여부는 사전에 확인이 필요합니다.",
    after:
      "시술 후 공통으로 시술 부위 안정을 위해 당일은 무리한 활동을 피하고, 지혈 부위를 압박·고정합니다. [관상동맥조영술/스텐트 삽입술] 시술 부위(손목 또는 사타구니)를 일정 시간 압박 고정하며, 지혈 후에도 당일은 무리한 걸음이나 운전을 피해주세요. [내시경 용종절제술] 절제 부위 출혈 예방을 위해 시술 후 며칠간 자극적인 음식과 무리한 운동, 항응고제 재복용을 피하고 의료진 안내를 따릅니다. [중심정맥관/케모포트 삽입술] 삽입 부위 소독과 드레싱 교체 주기를 의료진 안내에 따라 지키며, 발적·부종·발열이 있으면 즉시 알려주세요.",
    // "시술"은 "수술" 카테고리 필터 안에 있지만 서로 다른 개념이라, 이 콘텐츠에서
    // 노출되는 "수술" 문구(구간 라벨, 상단 배지·배너)는 전부 "시술"로 재정의합니다.
    phaseLabelOverride: { before: "시술 전", after: "시술 후" },
    categoryLabelOverride: "시술",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 3,
    lastUpdated: "2026-09-19",
  },

  // ───────────────────── 입원 (6) ─────────────────────
  {
    contentId: "c26",
    slug: "hospital-life",
    title: "입원생활 안내",
    category: "입원",
    subcategory: "입원생활 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "입원 준비물부터 복약 관리, 병실 생활 에티켓, 환자복·침구 교환, 식사, 면회 안내까지 입원생활 전반을 한 번에 안내합니다.",
    importantNotice:
      "복용 중인 모든 약(처방약·건강기능식품 포함)은 입원 시 반드시 간호사에게 알려주시고, 확인 전까지 임의로 복용하지 마세요.",
    before:
      "입원 준비물: 신분증, 개인 세면도구, 여벌 속옷, 지참약(있는 경우)을 준비해주세요. 복용 중인 약: 처방약과 건강기능식품을 포함해 복용 중인 모든 약을 입원 시 간호사에게 전달해 주시고, 자가약을 임의로 복용하지 마세요.",
    during:
      "환자복 및 침구는 정기적으로 교환해드리며, 오염되었거나 교환이 필요하면 담당 간호사에게 요청하세요. 식사는 입원 중 처방된 식이(일반식·치료식 등)에 맞춰 병동에서 제공되며, 알레르기나 종교상 제한 식품이 있으면 미리 간호사에게 알려주세요. 다른 환자를 배려하는 병실 생활 에티켓도 함께 지켜주세요: TV·라디오 시청 시에는 이어폰을 사용하고, 전화 통화는 작은 목소리로 짧게 하거나 복도·지정 장소를 이용해주세요. 휴대전화는 항상 진동 모드로 설정하고, 침상 주변은 다른 환자와 보호자의 이동에 방해되지 않도록 정리정돈해주세요. 병동 공용 냉장고에 음식을 보관할 때는 냄새와 오염 방지를 위해 밀폐용기를 사용해주세요.",
    after:
      "감염관리를 위한 보건복지부 지침에 따라 입원 기간 중 지정된 보호자 1명을 제외한 방문객의 면회를 전면 제한합니다. 간호간병통합병동은 보호자 상주가 제한됩니다.",
    faq: [
      {
        question: "자가약은 계속 먹어도 되나요?",
        answer: "담당 의료진이 확인 후 복용 가능 여부를 알려드립니다. 확인 전까지는 임의로 복용하지 마세요.",
      },
      {
        question: "보호자가 병실에 상주할 수 있나요?",
        answer: "일반병동은 보호자 상주가 가능하나, 간호간병통합병동은 전담 인력이 간호·간병을 제공해 보호자 상주가 제한됩니다.",
      },
    ],
    location: "각 병동 안내데스크",
    contact: "원무팀 입원계 02-2290-8114",
    relatedContentIds: ["c27", "c34", "c48"],
    estimatedReadMinutes: 4,
    status: "게시",
    needsClinicalReview: false,
    version: 3,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c27",
    slug: "ward-facilities",
    title: "편의시설 안내",
    category: "입원",
    subcategory: "편의시설 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "고객서비스센터, 건강 라운지, 식당·편의점, 물품 대여 등 병원 내 주요 편의시설 위치를 위치별로 한눈에 안내합니다.",
    before:
      "[본관] 1층: 고객서비스센터, 스마트 고객건강라운지(혈압·키·몸무게 측정), 할리스커피, 안내데스크(휠체어 대여). 3층: 무인 민원발급기, 오피스센터(팩스·PC 이용), HY수유실. [서관] 4·5·6층: 자동혈압계. 6층: 스마트 고객건강라운지. [동관] 1층: 마이델플레이스(한식·중식), 파리바게뜨, 세븐일레븐(편의점), 안내데스크(휠체어 대여). [영상 CD 등록기] 본관 3층 신경외과 외래 앞, 영상의학과 접수 앞, 서관 4층 심장내과 외래 앞, 본관 1층 엘리베이터 앞, 동관 1층 류마티스내과 외래 앞. 병실 내 냉장고·TV·샤워실 등의 이용 방법은 병동 간호사실에 문의해주세요.",
    phaseLabelOverride: { before: "편의시설 한눈에 보기" },
    faq: [{ question: "휠체어는 어디서 빌릴 수 있나요?", answer: "본관 1층 또는 동관 1층 안내데스크에서 대여할 수 있습니다." }],
    location: "한양대학교병원",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: false,
    version: 3,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c29",
    slug: "fall-prevention",
    title: "낙상예방 안내",
    category: "입원",
    subcategory: "낙상예방 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "입원 중 낙상을 예방하기 위한 생활 수칙을 안내합니다.",
    importantNotice: "어지러움이 있을 때는 침대에서 천천히 일어나고, 필요 시 호출벨로 도움을 요청하세요.",
    before: "거동이 어려우신 경우 이동 시 보호자분의 도움이 필요합니다. 미끄럼 방지 신발을 착용하며, 발에 맞는 신발을 착용합니다.",
    faq: [
      {
        question: "화장실은 혼자 가도 되나요?",
        answer: "어지럽거나 거동이 불편하다면 반드시 호출벨을 눌러 도움을 받은 후 이동하세요.",
      },
    ],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c30",
    slug: "patient-safety-id",
    title: "환자 안전",
    category: "입원",
    subcategory: "환자 안전",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "정확한 환자 확인과 나의 건강정보 전달에 함께 협조해주실 것을 안내합니다.",
    importantNotice: "입원 후 모든 순간이 치료결정과정 참여입니다.",
    before:
      "환자 안전을 위해 환자 확인이 필요한 단계마다 이름과 등록번호를 확인합니다. 이름과 등록번호를 말씀해 주세요. 직접 말씀하기 어려우신 환자분의 경우 보호자분과 함께 확인합니다.",
    during: "현재 주요 증상, 과거 질환, 알러지 반응 등 건강 정보를 의료진에게 말씀해 주세요.",
    phaseLabelOverride: { before: "정확한 환자 확인 함께하기", during: "정확한 나의 정보 알려주기" },
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c33",
    slug: "infection-control",
    title: "감염 예방 및 손위생 안내",
    category: "입원",
    subcategory: "감염 예방 및 손위생 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "기침 예절과 올바른 손씻기 등 병원 내 감염 예방 수칙을 안내합니다.",
    importantNotice: "발열, 기침 등 감염 의심 증상이 있으면 병실 이동 전 반드시 담당 의료진에게 먼저 알려주세요.",
    before:
      "기침이나 재채기가 나올 때는 휴지나 옷소매로 입과 코를 가려주세요. 사용한 휴지는 바로 휴지통에 버리고 손을 씻어주세요. 안내에 따라 마스크 착용이 필요한 경우 착용해주세요.",
    during:
      "병실 출입 전후, 식사 전, 화장실 사용 후에는 감염예방을 위해 손세정제를 이용하여 손을 씻거나 손소독제로 손위생을 해주시기 바랍니다.",
    phaseLabelOverride: { before: "감염예방", during: "올바른 손씻기" },
    faq: [
      {
        question: "손 소독제는 어디에 있나요?",
        answer: "병실 입구와 병동 곳곳에 비치되어 있으며, 부족하면 담당 간호사에게 요청하세요.",
      },
    ],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c34",
    slug: "integrated-nursing-care",
    title: "간호간병통합서비스 이용 안내",
    category: "입원",
    subcategory: "간호간병통합서비스 이용 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "보호자 상주 없이 전담 인력이 간호·간병을 제공하는 서비스를 안내합니다.",
    location: "간호간병통합서비스 병동",
    contact: "병동 안내데스크",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-07-01",
  },

  // ───────────────────── 퇴원 (8) ─────────────────────
  {
    contentId: "c35",
    slug: "discharge-guide",
    title: "퇴원 안내",
    category: "퇴원",
    subcategory: "퇴원 안내",
    departments: ["전과공통", "원무팀"],
    patientStages: ["before-discharge"],
    summary: "퇴원 당일 수속 절차와 준비물을 안내합니다.",
    before: "퇴원 결정 후 원무팀에서 수속을 진행하며, 개인 소지품을 미리 정리해주세요.",
    location: "본관 3층 원무팀",
    contact: "원무팀 퇴원계 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c36",
    slug: "life-after-discharge",
    title: "퇴원 후 생활 안내",
    category: "퇴원",
    subcategory: "퇴원 후 생활",
    departments: ["전과공통"],
    patientStages: ["after-discharge"],
    summary: "퇴원 후 일상 복귀 시 참고할 생활 수칙을 안내합니다.",
    after: "무리한 활동은 피하고, 컨디션에 맞춰 점진적으로 일상생활을 재개하세요.",
    importantNotice: "퇴원 후 발열, 평소와 다른 증상이 있다면 외래 방문 전이라도 병원에 문의하세요.",
    relatedContentIds: ["c37", "c38"],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c37",
    slug: "outpatient-followup",
    title: "외래 재진 및 예약 안내",
    category: "퇴원",
    subcategory: "외래 재진 및 예약 안내",
    departments: ["전과공통", "원무팀"],
    patientStages: ["before-discharge", "after-discharge"],
    summary: "퇴원 후 경과 확인을 위한 외래 방문 일정을 안내합니다.",
    contact: "진료예약(ARS) 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c38",
    slug: "medication-guide",
    title: "복약 안내",
    category: "퇴원",
    subcategory: "복약 안내",
    departments: ["전과공통"],
    patientStages: ["after-discharge"],
    summary: "퇴원 처방약 복용 시간과 놓쳤을 때 대처법을 안내합니다.",
    importantNotice: "임의로 약 복용을 중단하거나 용량을 조절하지 마세요.",
    before: "처방받은 시간에 맞춰 규칙적으로 복용해주세요.",
    faq: [{ question: "복용을 깜빡했어요.", answer: "생각난 즉시 복용하되, 다음 복용 시간과 가까우면 한 번만 복용하세요." }],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c39",
    slug: "er-visit-criteria",
    title: "재방문 및 응급실 내원 기준 안내",
    category: "퇴원",
    subcategory: "재방문 및 응급실 내원 기준 안내",
    departments: ["전과공통"],
    patientStages: ["after-discharge"],
    summary: "퇴원 후 응급실을 바로 방문해야 하는 위험 신호를 안내합니다.",
    importantNotice: "고열, 심한 통증, 호흡곤란, 심한 출혈이 있으면 지체 없이 응급실을 방문하세요.",
    contact: "응급 상황 시 119, 응급실 문의 대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c40",
    slug: "discharge-medication-pickup",
    title: "퇴원약 수령 안내",
    category: "퇴원",
    subcategory: "퇴원약 수령",
    departments: ["원무팀"],
    patientStages: ["before-discharge"],
    summary: "퇴원 시 처방약을 수령하는 절차와 위치를 안내합니다.",
    location: "본관 1층 외래약국",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c41",
    slug: "wound-care-after-discharge",
    title: "퇴원 후 상처 소독 관리 안내",
    category: "퇴원",
    subcategory: "퇴원 후 상처 소독 관리 안내",
    departments: ["외과", "정형외과"],
    patientStages: ["after-discharge"],
    summary: "퇴원 후 가정에서의 상처 소독 및 관리 방법을 안내합니다.",
    after: "손을 깨끗이 씻은 후 처방받은 소독법에 따라 관리해주세요.",
    importantNotice: "진물, 발적, 열감이 심해지면 즉시 병원에 방문하세요.",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c42",
    slug: "discharge-billing",
    title: "퇴원 수속 및 비용 정산 안내",
    category: "퇴원",
    subcategory: "퇴원 수속 및 비용정산",
    departments: ["원무팀"],
    patientStages: ["before-discharge"],
    summary: "퇴원 시 진료비 정산 절차와 결제 방법을 안내합니다.",
    location: "본관 3층 원무팀 퇴원 창구",
    contact: "원무팀 퇴원계 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },

  // ───────────────────── 기타 (8) ─────────────────────
  {
    contentId: "c43",
    slug: "find-test-room",
    title: "검사실 찾아가기",
    category: "기타",
    subcategory: "검사실 찾아가기",
    departments: ["전과공통"],
    patientStages: [],
    summary: "동·층별 주요 검사실 위치를 안내합니다.",
    location: "본관 2~3층(영상의학과·핵의학과), 서관 6층(내시경센터)",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c44",
    slug: "find-clinic-room",
    title: "진료실 찾아가기",
    category: "기타",
    subcategory: "진료실 찾아가기",
    departments: ["전과공통"],
    patientStages: [],
    summary: "동·층별 진료과 위치를 안내합니다.",
    location: "본관 각 층 안내도 참고",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c45",
    slug: "registration-payment",
    title: "원무팀 접수·수납 안내",
    category: "기타",
    subcategory: "원무팀 접수, 수납 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "외래 접수와 수납 절차, 무인수납기 이용 방법을 안내합니다.",
    location: "본관 1층 고객서비스센터, 각 층 수납창구",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c46",
    slug: "guardian-guide",
    title: "보호자 안내",
    category: "기타",
    subcategory: "보호자 안내",
    departments: ["전과공통"],
    patientStages: [],
    summary: "검사·수술 시 보호자 동행 및 대기 안내입니다.",
    location: "각 검사실·수술실 보호자 대기공간",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c47",
    slug: "medical-records",
    title: "의무기록 발급 및 제증명 서류 안내",
    category: "기타",
    subcategory: "의무기록 발급 및 제증명 서류 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "진단서, 소견서 등 제증명 서류 발급 절차와 소요 시간을 안내합니다.",
    location: "본관 3층 원무팀 (무인 제증명 발급기)",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c48",
    slug: "parking-transit",
    title: "주차 및 대중교통 이용 안내",
    category: "기타",
    subcategory: "주차 및 대중교통 이용 안내",
    departments: ["전과공통"],
    patientStages: [],
    summary: "병원 주차장 이용 방법과 대중교통 경로를 안내합니다.",
    location: "본관·동관·타워주차장",
    contact: "주차 문의 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c49",
    slug: "non-covered-costs",
    title: "비급여 진료비용 및 실손보험 안내",
    category: "기타",
    subcategory: "비급여 진료비용 및 실손보험 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "비급여 항목의 비용 안내와 실손보험 서류 준비 방법을 안내합니다.",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c50",
    slug: "referral-center",
    title: "진료협력센터(타 병원 의뢰) 안내",
    category: "기타",
    subcategory: "진료협력센터(타 병원 의뢰) 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "타 병원 진료 의뢰서 발급과 진료협력센터 이용 방법을 안내합니다.",
    location: "본관 1층 진료협력센터",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
];

export function findGuideBySlug(slug: string): GuideContent | undefined {
  return GUIDES.find((g) => g.slug === slug);
}
