import type { GuideContent } from "./types";

/**
 * 프로토타입용 Mock 콘텐츠입니다. 구체적인 수치(금식 시간, 복용법 등)는
 * 예시이며, 실제 게시 전 반드시 병원 공식 검토(주치의/간호부/약제부 등)를
 * 거쳐야 합니다. `needsClinicalReview: true` 항목은 특히 더 필요합니다.
 *
 * Phase 1에서는 환자 데이터와 연결하지 않습니다. `slug`는 환자에게
 * 전달되는 고정 URL(/c/[slug])에 쓰이며 개인정보를 포함하지 않습니다.
 */
export const GUIDES: GuideContent[] = [
  // ───────────────────── 검사 (15) ─────────────────────
  {
    contentId: "c01",
    slug: "ct-prep",
    title: "CT 검사 안내",
    category: "검사",
    subcategory: "CT",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "조영제 사용 여부에 따른 금식 시간부터 검사 당일 절차, 검사 후 주의사항까지 CT 검사 전 과정을 안내합니다.",
    importantNotice:
      "조영제를 사용하는 검사인 경우 금속 신장질환·조영제 알레르기·임신 여부·당뇨약(메트포르민 성분) 복용 여부를 검사 전 반드시 알려주셔야 합니다.",
    before:
      "조영제를 사용하는 CT는 검사 4~6시간 전부터 금식이 필요하며, 조영제를 사용하지 않는 CT(뼈·흉부 등 단순 촬영)는 별도의 금식이 필요 없는 경우가 많습니다. 검사 예약 시 안내받은 금식 시간을 확인해주세요. 임신 가능성, 조영제 알레르기 병력, 신장질환, 당뇨약 복용 여부는 예약 시 또는 검사 전 접수 시 반드시 알려주세요. 금속 장신구·보청기·틀니 등은 미리 제거해 오시면 대기 시간이 줄어듭니다.",
    during:
      "검사 전 영상의학과 접수처에 방문해 접수해주세요. 환복이 필요한 경우 검사복으로 갈아입고 대기합니다. 조영제를 사용하는 경우 팔 정맥에 주사로 주입하며, 주입 시 몸이 따뜻해지거나 입안에서 금속 맛이 느껴질 수 있는데 이는 대부분 일시적인 정상 반응입니다. 검사 자체는 10~20분 내외로 짧지만, 상황에 따라 시간이 달라질 수 있습니다.",
    after:
      "조영제를 사용한 경우 체내 배출을 돕기 위해 검사 후 충분한 수분(물) 섭취를 권장합니다. 특별한 활동 제한은 없어 검사 후 바로 일상생활이 가능합니다. 다만 검사 후 수 시간 내 두드러기, 가려움, 호흡곤란 등 지연성 알레르기 반응이 나타날 수 있으니, 증상이 있으면 즉시 영상의학과 또는 응급실로 연락해주세요. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    faq: [
      { question: "물은 마셔도 되나요?", answer: "검사 전 소량의 물은 대부분 허용되나, 조영제 사용 여부에 따라 다르므로 담당 부서 안내를 우선 따르세요." },
      { question: "조영제 부작용이 걱정돼요.", answer: "가려움·두드러기 같은 경미한 반응이 흔하지만, 호흡곤란처럼 심한 반응은 드뭅니다. 알레르기 병력이 있다면 검사 전 반드시 미리 알려주시면 예방 조치를 받을 수 있습니다." },
      { question: "임신 중인데 CT를 찍어도 되나요?", answer: "임신(가능성 포함) 사실은 예약 또는 접수 시 반드시 먼저 알려주세요. 방사선 노출을 고려해 검사 방법이 조정되거나 다른 검사로 대체될 수 있습니다." },
    ],
    location: "본관 3층 영상의학과 CT촬영실",
    contact: "영상의학과 검사예약 02-2290-8114",
    relatedContentIds: ["c10", "c14"],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-18",
  },
  {
    contentId: "c02",
    slug: "mri-prep",
    title: "MRI 검사 안내",
    category: "검사",
    subcategory: "MRI",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "조영제 사용 여부에 따른 금식 시간부터 검사 당일 절차, 검사 후 주의사항까지 MRI 검사 전 과정을 안내합니다.",
    importantNotice:
      "체내 금속 삽입물(인공관절, 심장박동기, 인공와우, 신경자극기 등)이나 문신·반영구화장이 있는 경우 반드시 사전에 알려주세요.",
    before:
      "검사 전 화장, 금속성 액세서리(귀걸이, 목걸이, 벨트 등)는 제거해주세요. 폐쇄공포감이 있다면 검사 전 미리 의료진에게 알려주시면 안정을 돕는 방법을 안내받을 수 있습니다.",
    during:
      "검사는 부위에 따라 20~40분 소요되며, 검사 중 매우 큰 소음이 발생하므로 준비된 귀마개나 헤드폰을 착용합니다. 조영제를 사용하는 경우 검사 중간에 정맥주사로 투여됩니다.",
    after:
      "검사 후 특별한 활동 제한 없이 바로 일상생활이 가능합니다. 조영제를 사용한 경우 배출을 돕기 위해 충분한 수분 섭취를 권장합니다. 검사 결과는 예약된 진료일에 담당 교수님을 통해 안내받습니다.",
    faq: [{ question: "폐쇄공포증이 있는데 검사가 가능한가요?", answer: "사전에 알려주시면 진정제 사용이나 개방형 MRI 등 대안을 상의할 수 있습니다." }],
    location: "본관 3층 영상의학과 MRI촬영실",
    contact: "영상의학과 검사예약 02-2290-8114",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c03",
    slug: "xray-prep",
    title: "X-ray 검사 안내",
    category: "검사",
    subcategory: "X-ray",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "X-ray 촬영 시 준비사항과 소요 시간을 안내합니다.",
    before: "촬영 부위에 금속(단추, 지퍼, 액세서리)이 없도록 준비해주세요.",
    during: "촬영은 부위당 5분 이내로 짧게 진행되며, 안내에 따라 자세를 잡고 잠시 숨을 참게 됩니다.",
    after: "촬영 후 특별한 제한 없이 바로 일상생활이 가능합니다. 결과는 담당 진료과 진료 시 함께 안내받습니다.",
    location: "본관 3층 영상의학과 일반촬영실",
    contact: "영상의학과 검사예약 02-2290-9738",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c04",
    slug: "ultrasound-prep",
    title: "초음파 검사 안내",
    category: "검사",
    subcategory: "초음파",
    departments: ["영상의학과", "내과"],
    patientStages: ["before-test"],
    summary: "복부·갑상선 등 초음파 검사별 준비사항을 안내합니다.",
    importantNotice: "복부 초음파는 검사 종류에 따라 금식이 필요할 수 있습니다.",
    before: "담당 부서에서 안내한 금식·수분 섭취 기준을 확인해주세요.",
    during:
      "검사 부위에 젤을 바른 뒤 탐촉자로 부위를 눌러가며 촬영하며, 통증 없이 10~20분 정도 소요됩니다. 검사 중 자세를 바꾸거나 숨을 참으라는 안내가 있을 수 있습니다.",
    after: "젤을 닦아내면 바로 일상생활이 가능하며 별도의 주의사항은 없습니다. 결과는 담당 진료과에서 안내받습니다.",
    location: "본관 3층 영상의학과 초음파검사실",
    contact: "영상의학과 검사예약 02-2290-9738",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c05",
    slug: "gastroscopy-prep",
    title: "위내시경 검사 안내",
    category: "검사",
    subcategory: "위내시경",
    departments: ["소화기내과"],
    patientStages: ["before-test"],
    summary: "위내시경 검사 절차와 진정 내시경 여부에 따른 주의사항을 안내합니다.",
    before: "검사 전 8시간 금식이 필요합니다(물 포함, 담당 부서 안내 우선).",
    during: "진정 내시경으로 진행하는 경우, 검사 후 직접 운전은 삼가고 보호자와 동행해주세요.",
    after: "검사 후 목 이물감이 있을 수 있으며 대부분 자연히 호전됩니다.",
    faq: [{ question: "혈압약은 먹어도 되나요?", answer: "소량의 물과 함께 복용 가능한 경우가 많으나, 담당 의료진 확인이 필요합니다." }],
    location: "서관 6층 소화기 내시경 검사실",
    contact: "소화기내과 검사예약 02-2290-9738",
    relatedContentIds: ["c07", "c46"],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-08-01",
  },
  {
    contentId: "c06",
    slug: "colonoscopy-prep",
    title: "대장내시경 검사 안내",
    category: "검사",
    subcategory: "대장내시경",
    departments: ["소화기내과"],
    patientStages: ["before-test"],
    summary: "대장내시경 검사를 위한 장 정결 준비 절차를 안내합니다.",
    importantNotice: "장 정결제는 처방받은 시간과 방법을 반드시 지켜서 복용해주세요.",
    before: "검사 전날 저녁부터 저잔사식 위주로 섭취하고, 처방된 장 정결제를 복용합니다.",
    during: "검사 당일에는 물 이외의 음식 섭취를 피해주세요.",
    after: "가스가 찬 느낌이 있을 수 있으며 시간이 지나면 호전됩니다.",
    location: "서관 6층 소화기 내시경 검사실",
    contact: "소화기내과 검사예약 02-2290-9738",
    relatedContentIds: ["c05", "c46"],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-08-01",
  },
  {
    contentId: "c07",
    slug: "blood-test",
    title: "채혈 및 임상검사 안내",
    category: "검사",
    subcategory: "채혈 및 임상검사",
    departments: ["진단검사의학과", "전과공통"],
    patientStages: ["before-test", "admitted"],
    summary: "채혈 검사 전후 확인 사항을 안내합니다.",
    before: "검사 항목에 따라 8~12시간 금식이 필요할 수 있습니다.",
    during:
      "채혈실 순번에 따라 이름과 등록번호를 확인한 뒤 진행하며, 검사 항목에 따라 1~3개 튜브 정도의 혈액을 채취합니다. 소요 시간은 5분 이내로 짧습니다.",
    after: "채혈 부위는 5분 이상 지그시 눌러 지혈해주세요.",
    location: "본관 3층 진단검사의학과 채혈실",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c08",
    slug: "biopsy-prep",
    title: "조직검사 안내",
    category: "검사",
    subcategory: "조직검사",
    departments: ["외과", "소화기내과"],
    patientStages: ["before-test"],
    summary: "조직검사 절차와 결과 확인까지 걸리는 기간을 안내합니다.",
    importantNotice: "항응고제(혈액을 묽게 하는 약) 복용 중이라면 검사 전 반드시 의료진과 상의해주세요.",
    before:
      "항응고제나 아스피린 계열 약물을 복용 중이라면 검사 며칠 전부터 중단이 필요할 수 있으니 사전에 반드시 담당 의료진과 상의해주세요. 검사 부위에 따라 금식이 필요할 수 있습니다.",
    during:
      "국소마취 후 바늘이나 특수 기구로 조직을 채취하며, 부위에 따라 10~30분 정도 소요됩니다. 검사 중 눌리는 느낌이나 약간의 통증이 있을 수 있습니다.",
    after: "검사 부위 통증이나 소량의 출혈이 있을 수 있으며, 결과는 통상 5~7일 소요됩니다.",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c09",
    slug: "pet-ct-prep",
    title: "PET-CT 검사 안내",
    category: "검사",
    subcategory: "PET-CT",
    departments: ["핵의학과"],
    patientStages: ["before-test"],
    summary: "방사성의약품을 이용한 PET-CT 검사 준비사항을 안내합니다.",
    importantNotice: "검사 전날부터 격렬한 운동을 피하고, 당일 검사 전 6시간 금식이 필요합니다.",
    before: "혈당이 높으면 검사가 지연될 수 있어, 당뇨가 있는 경우 사전에 알려주세요.",
    during: "약물 주입 후 1시간가량 안정을 취한 뒤 촬영이 진행되며, 촬영 자체는 20~30분 정도 소요됩니다.",
    after:
      "검사 후 방사성의약품 배출을 돕기 위해 충분한 수분을 섭취해주세요. 당일은 임산부·영유아와의 밀접 접촉을 피하는 것이 좋습니다. 결과는 예약된 진료일에 안내받습니다.",
    location: "본관 2층 핵의학과 PET-CT/감마카메라실",
    contact: "핵의학과 검사예약 02-2290-9738",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c10",
    slug: "contrast-media",
    title: "조영제 검사 및 부작용 안내",
    category: "검사",
    subcategory: "조영제 검사 및 부작용",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "조영제를 사용하는 검사 전 확인이 필요한 사항을 안내합니다.",
    importantNotice: "조영제 알레르기 반응 경험이 있거나 신장 기능에 이상이 있다면 반드시 검사 전 의료진에게 알려주세요.",
    before: "당뇨약(메트포르민 계열) 복용 중이라면 사전에 담당 의료진과 복용 중단 여부를 상의해주세요.",
    during:
      "검사 종류에 따라 정맥주사 또는 경구로 조영제를 투여하며, 투여 시 몸이 따뜻해지거나 금속 맛이 느껴질 수 있는데 대부분 일시적인 정상 반응입니다. 이상 증상이 느껴지면 즉시 의료진에게 알려주세요.",
    after: "조영제 배출을 돕기 위해 충분한 수분 섭취를 권장하며, 어지러움·두드러기 등 이상 반응 시 즉시 알려주세요.",
    location: "본관 2층 영상의학과 투시조영검사실",
    contact: "영상의학과 검사예약 02-2290-9738",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c11",
    slug: "ekg-prep",
    title: "심전도 검사 안내",
    category: "검사",
    subcategory: "심전도",
    departments: ["순환기내과"],
    patientStages: ["before-test"],
    summary: "심전도 검사 절차와 소요 시간을 안내합니다.",
    before: "검사 전 특별한 준비는 필요 없으나, 로션이나 오일 사용은 전극 부착을 방해할 수 있어 피해주세요.",
    during: "상의를 탈의하고 가슴, 팔, 다리에 전극을 부착해 5분 이내로 측정합니다.",
    after: "검사 후 특별한 제한 없이 바로 일상생활이 가능합니다. 결과는 담당 진료과에서 안내받습니다.",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c12",
    slug: "echocardiography-prep",
    title: "심장초음파 검사 안내",
    category: "검사",
    subcategory: "심장초음파",
    departments: ["순환기내과"],
    patientStages: ["before-test"],
    summary: "심장초음파 검사 준비사항과 소요 시간을 안내합니다.",
    before: "별도의 금식 없이 진행되나, 담당 부서 안내를 우선 확인해주세요.",
    during: "검사는 30분 내외로 진행되며 왼쪽으로 누운 자세를 취하게 됩니다.",
    after: "검사 후 특별한 제한 없이 바로 일상생활이 가능합니다. 젤은 닦아내시면 되며, 결과는 담당 진료과에서 안내받습니다.",
    location: "서관 5층 심장내과 심장초음파실",
    contact: "순환기내과 검사예약 02-2290-9738",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c13",
    slug: "nuclear-medicine-prep",
    title: "핵의학검사 안내",
    category: "검사",
    subcategory: "핵의학검사",
    departments: ["핵의학과"],
    patientStages: ["before-test"],
    summary: "뼈scan 등 핵의학검사 절차와 소요 시간을 안내합니다.",
    before: "방사성의약품 주입 후 촬영까지 대기 시간이 있을 수 있습니다.",
    during: "방사성의약품을 주사한 후 검사 종류에 따라 수십 분에서 몇 시간의 대기 시간을 거쳐 촬영을 진행합니다. 촬영 자체는 통증이 없습니다.",
    after: "검사 후 방사성의약품 배출을 돕기 위해 충분한 수분을 섭취해주세요. 당일은 임산부·영유아와의 밀접 접촉을 피해주세요.",
    location: "본관 2층 핵의학과",
    contact: "핵의학과 검사예약 02-2290-9738",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c14",
    slug: "fasting-guide",
    title: "검사 전 금식 가이드",
    category: "검사",
    subcategory: "검사 전 금식 가이드",
    departments: ["전과공통"],
    patientStages: ["before-test"],
    summary: "검사 종류별 금식 시간을 한눈에 정리한 공통 안내입니다.",
    importantNotice: "검사별 금식 시간이 다르므로 반드시 담당 부서 안내를 우선 확인해주세요.",
    before: "일반 채혈·초음파는 8시간, 내시경은 8시간, PET-CT는 6시간 금식이 일반적인 기준입니다(검사별 상이).",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-08-01",
  },
  {
    contentId: "c15",
    slug: "mammography-prep",
    title: "유방촬영(맘모그래피) 검사 안내",
    category: "검사",
    subcategory: "유방촬영(맘모그래피)",
    departments: ["영상의학과"],
    patientStages: ["before-test"],
    summary: "유방촬영 검사 시 준비사항과 촬영 시 유의사항을 안내합니다.",
    before: "검사 당일 데오드란트, 파우더 사용은 피해주세요.",
    during: "압박 촬영 시 일시적으로 불편감이 있을 수 있습니다.",
    after:
      "촬영 후 일시적으로 압박 부위가 눌린 느낌이 있을 수 있으나 곧 회복됩니다. 특별한 제한 없이 바로 일상생활이 가능하며, 결과는 담당 진료과에서 안내받습니다.",
    location: "본관 2층 영상의학과 유방촬영실",
    contact: "영상의학과 검사예약 02-2290-9738",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },

  // ───────────────────── 수술 (6) ─────────────────────
  {
    contentId: "c16",
    slug: "surgery-guide",
    title: "수술 안내",
    category: "수술",
    subcategory: "수술 전·중·후",
    departments: ["외과", "정형외과"],
    patientStages: ["before-surgery", "admitted"],
    summary: "입원 및 수술 전 준비물부터 수술 당일 절차, 수술 후 회복 과정까지 전 과정을 안내합니다.",
    importantNotice:
      "복용 중인 모든 약물(건강기능식품 포함)을 입원 시 의료진에게 알려주세요. 수술 후 심한 통증, 출혈, 고열이 있으면 즉시 담당 병동 간호사에게 알려주세요.",
    before:
      "수술 전날 자정부터 금식이 필요하며, 세부 시간은 담당 병동 안내를 따라주세요. 복용 중인 모든 약물(건강기능식품 포함)은 입원 시 의료진에게 알려주시고, 의료진 확인 없이 임의로 복용을 중단하거나 지속하지 마세요. 수술 동의서 작성과 마취 사전 상담은 별도 안내에 따라 진행됩니다.",
    during:
      "수술 당일 아침 병동에서 환복, 정맥주사 확보 등 수술 준비를 마친 후 수술 준비실로 이동하며, 이동 전 마취과 의료진의 최종 확인 절차를 거칩니다. 보호자는 본관 3층 수술실 보호자 대기실에서 대기하실 수 있으며, 수술이 끝나면 담당의가 직접 결과를 안내합니다.",
    after:
      "마취 회복 후 의료진 지시에 따라 단계적으로 식이를 진행하며, 통증·배액관·상처 상태를 의료진이 주기적으로 확인합니다. 심한 통증, 출혈, 고열이 있으면 즉시 담당 병동 간호사에게 알려주세요.",
    faq: [
      {
        question: "보호자는 수술 중 어디서 기다리나요?",
        answer: "본관 3층 수술실 보호자 대기실에서 대기하실 수 있으며, 상황에 따라 수술 중간에 경과를 안내받을 수 있습니다.",
      },
    ],
    location: "본관 3층 수술실·수술실 보호자 대기실",
    relatedContentIds: ["c19", "c21", "c22", "c23"],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c19",
    slug: "post-surgery-recovery",
    title: "수술 후 회복 관리 안내",
    category: "수술",
    subcategory: "수술 후 통증·식사·재활",
    departments: ["외과", "정형외과", "마취통증의학과", "재활의학과"],
    patientStages: ["admitted", "after-discharge"],
    summary: "수술 후 통증 조절, 단계별 식이 진행, 재활운동과 폐 합병증 예방(인스피로미터 사용법)까지 회복 전 과정을 안내합니다.",
    importantNotice:
      "통증을 참기보다 담당 의료진에게 통증 정도를 알려 적절한 조절을 받으시고, 무리한 운동은 오히려 회복을 늦출 수 있으니 반드시 담당 의료진의 운동 처방을 따르세요.",
    during:
      "수술 직후에는 통증을 참기보다 담당 의료진에게 통증 정도를 알려 적절한 조절을 받으세요. 자가 통증 조절 장치(PCA)를 사용하는 경우 사용법을 담당 간호사에게 안내받으며, 정해진 용량 안에서 스스로 조절할 수 있습니다.",
    after:
      "장 기능 회복 정도에 따라 의료진이 금식→유동식→일반식 순으로 식이를 단계적으로 조절합니다. 폐 합병증(폐렴, 무기폐) 예방을 위해 인스피로미터(폐활량 운동기구)를 하루 여러 차례 사용해주세요: 마우스피스를 입에 물고 천천히 최대한 깊게 들이마셔 공이나 피스톤을 목표 높이까지 끌어올린 뒤 2~3초간 유지하고 천천히 내쉽니다. 이 외에도 의료진이 안내하는 범위 내에서 단계적으로 관절 운동 범위를 늘려가며, 무리한 운동은 오히려 회복을 늦출 수 있으니 반드시 담당 의료진의 운동 처방을 따르세요.",
    faq: [
      {
        question: "인스피로미터는 왜 사용하나요?",
        answer:
          "수술 후 얕은 호흡이 지속되면 폐렴 등 폐 합병증 위험이 높아집니다. 인스피로미터로 깊은 호흡을 반복 연습하면 폐가 완전히 펴지는 데 도움이 되어 합병증을 예방할 수 있습니다.",
      },
    ],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c21",
    slug: "discharge-wound-care",
    title: "퇴원 준비 및 수술부위 관리",
    category: "수술",
    subcategory: "퇴원 준비 및 퇴원후 수술부위관리",
    departments: ["외과", "정형외과"],
    patientStages: ["before-discharge", "after-discharge"],
    summary: "퇴원 후 수술 부위 소독과 드레싱 교체 주기를 안내합니다.",
    after: "드레싱은 담당 의료진이 안내한 주기에 맞춰 교체합니다.",
    importantNotice: "상처 부위에 발적, 진물, 열감이 있으면 감염 가능성이 있으니 즉시 병원에 문의하세요.",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-07-15",
  },
  {
    contentId: "c22",
    slug: "surgery-consent",
    title: "수술 동의서 작성 및 설명 안내",
    category: "수술",
    subcategory: "수술 동의서작성 및 설명안내",
    departments: ["외과", "정형외과", "원무팀"],
    patientStages: ["before-surgery"],
    summary: "수술 동의서 작성 절차와 필요 서류를 안내합니다.",
    before: "집도의의 수술 설명을 들은 후 환자 본인 또는 법정대리인이 서명합니다.",
    location: "본관 3층 원무팀 입원 수속 창구",
    contact: "원무팀 입원계 02-2290-9072~4",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-07-15",
  },
  {
    contentId: "c23",
    slug: "anesthesia-consultation",
    title: "수술 전 마취 사전 상담 안내",
    category: "수술",
    subcategory: "수술 전 마취 사전 상담 안내",
    departments: ["마취통증의학과"],
    patientStages: ["before-surgery"],
    summary: "마취 방법과 위험도를 사전에 확인하는 상담 절차를 안내합니다.",
    before: "기존 질환, 복용 약물, 마취 관련 과거력을 상담 시 정확히 알려주세요.",
    location: "마취통증의학과 외래",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-07-15",
  },
  {
    contentId: "c24",
    slug: "procedure-before-after",
    title: "시술 전후 안내",
    category: "수술",
    subcategory: "전후 관리",
    departments: ["외과", "내과", "순환기내과"],
    patientStages: ["before-surgery", "admitted"],
    summary: "수술보다 회복이 짧은 시술(내시경 시술 등)의 전후 유의사항을 안내합니다.",
    before: "시술 종류에 따라 금식·항응고제 중단이 필요할 수 있습니다.",
    after: "시술 부위 안정을 위해 당일은 무리한 활동을 피해주세요.",
    // "시술"은 "수술" 카테고리 필터 안에 있지만 서로 다른 개념이라, 이 콘텐츠에서
    // 노출되는 "수술" 문구(구간 라벨, 상단 배지·배너)는 전부 "시술"로 재정의합니다.
    phaseLabelOverride: { before: "시술 전", after: "시술 후" },
    categoryLabelOverride: "시술",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 2,
    lastUpdated: "2026-09-19",
  },

  // ───────────────────── 입원 (9) ─────────────────────
  {
    contentId: "c26",
    slug: "hospital-life",
    title: "입원생활 안내",
    category: "입원",
    subcategory: "입원생활 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "입원 준비물부터 복약 관리, 환자복·침구 교환, 식사, 보호자 면회, 주차까지 입원생활 전반을 한 번에 안내합니다.",
    importantNotice:
      "복용 중인 모든 약(처방약·건강기능식품 포함)은 입원 시 반드시 간호사에게 알려주시고, 확인 전까지 임의로 복용하지 마세요.",
    before:
      "입원 준비물: 신분증, 개인 세면도구, 여벌 속옷, 상비약(있는 경우)을 준비해주세요. 고가품·귀중품은 되도록 가져오지 마시고, 부득이한 경우 병동에 보관을 문의하세요. 복용 중인 약: 처방약과 건강기능식품을 포함해 복용 중인 모든 약을 입원 시 간호사에게 전달해 확인받으시고, 확인 전까지는 자가약을 임의로 복용하지 마세요.",
    during:
      "환자복 및 침구는 정기적으로 교환해드리며, 오염되었거나 교환이 필요하면 담당 간호사에게 요청하세요. 식사는 입원 중 처방된 식이(일반식·치료식 등)에 맞춰 병동에서 제공되며, 알레르기나 종교상 제한 식품이 있으면 미리 간호사에게 알려주세요. 외부 음식 반입은 담당 의료진과 상의 후 결정해주세요.",
    after:
      "보호자 출입 및 면회 시간, 상주 인원 규정은 병동별로 다를 수 있으니 병동 게시판이나 간호사실에서 확인해주세요(간호간병통합병동은 보호자 상주가 제한됩니다). 주차는 입원 당일 입차 기준 24시간 무료이며(1대, 1회 입출차), 입원 기간 중 추가 주차는 유료입니다.",
    faq: [
      {
        question: "자가약은 계속 먹어도 되나요?",
        answer: "담당 의료진이 확인 후 복용 가능 여부를 알려드립니다. 확인 전까지는 임의로 복용하지 마세요.",
      },
      {
        question: "보호자가 병실에 상주할 수 있나요?",
        answer: "일반병동은 보호자 상주가 가능하나, 간호간병통합병동은 전담 인력이 간호·간병을 제공해 보호자 상주가 제한됩니다.",
      },
    ],
    location: "각 병동 안내데스크",
    contact: "원무팀 입원계 02-2290-9072~4",
    relatedContentIds: ["c27", "c32", "c34", "c48"],
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c27",
    slug: "ward-facilities",
    title: "편의시설 안내",
    category: "입원",
    subcategory: "편의시설 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "고객서비스센터, 건강 라운지, 식당·편의점, 물품 대여 등 병원 내 주요 편의시설 위치를 안내합니다.",
    before:
      "고객서비스센터: 본관 1층. 스마트 고객건강라운지(혈압·키·몸무게 측정): 본관 1층, 서관 6층. 자동혈압계: 서관 4·5·6층. 무인 민원발급기: 본관 3층. 오피스센터(팩스·PC 이용): 본관 3층. 영상 CD 등록기: 본관 3층 신경외과 외래 앞, 영상의학과 접수 앞, 서관 4층 심장내과 외래 앞, 본관 1층 엘리베이터 앞, 동관 1층 류마티스내과 외래 앞.",
    during:
      "식당·카페: 마이델플레이스(한식·중식) 동관 1층, 할리스커피 본관 1층, 파리바게뜨 동관 1층, 세븐일레븐(편의점) 동관 1층. 병실 내에는 냉장고, TV, 샤워실 등이 마련되어 있으며 이용 방법은 병동 간호사실에 문의해주세요.",
    after: "휠체어 대여: 본관 1층 안내데스크, 동관 1층 안내데스크. HY수유실: 본관 3층.",
    faq: [{ question: "휠체어는 어디서 빌릴 수 있나요?", answer: "본관 1층 또는 동관 1층 안내데스크에서 대여할 수 있습니다." }],
    location: "본관·서관·동관 각 층",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 3,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c28",
    slug: "hospital-etiquette",
    title: "병원생활에티켓",
    category: "입원",
    subcategory: "병원생활에티켓",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "다른 환자를 배려하는 병실 내 기본 에티켓(TV·라디오, 통화, 정리정돈, 냉장고 이용)을 안내합니다.",
    before:
      "TV·라디오 시청 시에는 이어폰을 사용해주세요. 전화 통화는 작은 목소리로 짧게 해주시고, 가능하면 복도나 지정 장소를 이용해주세요. 휴대전화는 항상 진동 모드로 설정해주세요. 침상 주변은 다른 환자와 보호자의 이동에 방해되지 않도록 정리정돈해주세요. 병동 공용 냉장고에 음식을 보관할 때는 냄새와 오염 방지를 위해 밀폐용기를 사용해주세요.",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 2,
    lastUpdated: "2026-09-19",
  },
  {
    contentId: "c29",
    slug: "fall-prevention",
    title: "낙상예방 안내",
    category: "입원",
    subcategory: "낙상예방 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "입원 중 낙상을 예방하기 위한 생활 수칙을 안내합니다.",
    importantNotice: "어지러움이 있을 때는 침대에서 천천히 일어나고, 필요 시 호출벨로 도움을 요청하세요.",
    before: "침대 난간은 항상 올려두고, 바닥의 물기나 전선·장애물을 치워 미끄럼을 예방하세요. 미끄럼 방지 신발을 착용하는 것도 도움이 됩니다.",
    faq: [
      {
        question: "화장실은 혼자 가도 되나요?",
        answer: "어지럽거나 거동이 불편하다면 반드시 호출벨을 눌러 도움을 받은 후 이동하세요.",
      },
    ],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-09-17",
  },
  {
    contentId: "c30",
    slug: "patient-safety-id",
    title: "환자안전 및 정확한 환자 확인 안내",
    category: "입원",
    subcategory: "환자안전 및 정확한 환자 확인",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "검사·투약 시 환자 확인 절차에 협조해주실 것을 안내합니다.",
    before: "의료진이 이름, 등록번호를 반복해서 확인하는 것은 안전을 위한 절차입니다.",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-07-01",
  },
  {
    contentId: "c31",
    slug: "transport-guide",
    title: "검사 및 시술 이동 안내",
    category: "입원",
    subcategory: "검사 및 시술 이동 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "입원 중 검사·시술실로 이동하는 절차를 안내합니다.",
    during: "이동 시 담당 병동 직원의 안내에 따라 이동하며, 필요 시 휠체어·이동식 침대가 제공됩니다.",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-07-01",
  },
  {
    contentId: "c32",
    slug: "self-medication",
    title: "입원 중 복약 및 자가약 관리 안내",
    category: "입원",
    subcategory: "입원 중 복약 및 자가약 관리",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "입원 중 자가 지참약 관리와 복약 시간 준수 방법을 안내합니다.",
    importantNotice: "집에서 가져온 약은 반드시 담당 의료진에게 알리고 확인받은 후 복용해주세요.",
    before: "입원 시 복용 중인 모든 약(처방약, 건강기능식품 포함)을 간호사에게 전달해 확인받으세요.",
    faq: [
      {
        question: "가져온 자가약을 계속 먹어도 되나요?",
        answer: "담당 의료진이 확인 후 복용 가능 여부를 알려드립니다. 확인 전까지는 임의로 복용하지 마세요.",
      },
    ],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-09-17",
  },
  {
    contentId: "c33",
    slug: "infection-control",
    title: "감염 예방 및 손위생 안내",
    category: "입원",
    subcategory: "감염 예방 및 손위생 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "병원 내 감염 예방을 위한 손위생 수칙을 안내합니다.",
    importantNotice: "발열, 기침 등 감염 의심 증상이 있으면 병실 이동 전 반드시 담당 의료진에게 먼저 알려주세요.",
    before: "병실 출입 전후, 식사 전, 화장실 사용 후 손 소독제를 사용해주세요.",
    faq: [
      {
        question: "손 소독제는 어디에 있나요?",
        answer: "병실 입구와 병동 곳곳에 비치되어 있으며, 부족하면 담당 간호사에게 요청하세요.",
      },
    ],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-09-17",
  },
  {
    contentId: "c34",
    slug: "integrated-nursing-care",
    title: "간호간병통합서비스 이용 안내",
    category: "입원",
    subcategory: "간호간병통합서비스 이용 안내",
    departments: ["전과공통"],
    patientStages: ["admitted"],
    summary: "보호자 상주 없이 전담 인력이 간호·간병을 제공하는 서비스를 안내합니다.",
    location: "간호간병통합서비스 병동",
    contact: "병동 안내데스크",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-07-01",
  },

  // ───────────────────── 퇴원 (8) ─────────────────────
  {
    contentId: "c35",
    slug: "discharge-guide",
    title: "퇴원 안내",
    category: "퇴원",
    subcategory: "퇴원 안내",
    departments: ["전과공통", "원무팀"],
    patientStages: ["before-discharge"],
    summary: "퇴원 당일 수속 절차와 준비물을 안내합니다.",
    before: "퇴원 결정 후 원무팀에서 수속을 진행하며, 개인 소지품을 미리 정리해주세요.",
    location: "본관 3층 원무팀",
    contact: "원무팀 퇴원계 02-2290-9076~7",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c36",
    slug: "life-after-discharge",
    title: "퇴원 후 생활 안내",
    category: "퇴원",
    subcategory: "퇴원 후 생활",
    departments: ["전과공통"],
    patientStages: ["after-discharge"],
    summary: "퇴원 후 일상 복귀 시 참고할 생활 수칙을 안내합니다.",
    after: "무리한 활동은 피하고, 컨디션에 맞춰 점진적으로 일상생활을 재개하세요.",
    importantNotice: "퇴원 후 발열, 평소와 다른 증상이 있다면 외래 방문 전이라도 병원에 문의하세요.",
    relatedContentIds: ["c37", "c38"],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c37",
    slug: "outpatient-followup",
    title: "외래 재진 및 예약 안내",
    category: "퇴원",
    subcategory: "외래 재진 및 예약 안내",
    departments: ["전과공통", "원무팀"],
    patientStages: ["before-discharge", "after-discharge"],
    summary: "퇴원 후 경과 확인을 위한 외래 방문 일정을 안내합니다.",
    contact: "진료예약(ARS) 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c38",
    slug: "medication-guide",
    title: "복약 안내",
    category: "퇴원",
    subcategory: "복약 안내",
    departments: ["전과공통"],
    patientStages: ["after-discharge"],
    summary: "퇴원 처방약 복용 시간과 놓쳤을 때 대처법을 안내합니다.",
    importantNotice: "임의로 약 복용을 중단하거나 용량을 조절하지 마세요.",
    before: "처방받은 시간에 맞춰 규칙적으로 복용해주세요.",
    faq: [{ question: "복용을 깜빡했어요.", answer: "생각난 즉시 복용하되, 다음 복용 시간과 가까우면 한 번만 복용하세요." }],
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c39",
    slug: "er-visit-criteria",
    title: "재방문 및 응급실 내원 기준 안내",
    category: "퇴원",
    subcategory: "재방문 및 응급실 내원 기준 안내",
    departments: ["전과공통"],
    patientStages: ["after-discharge"],
    summary: "퇴원 후 응급실을 바로 방문해야 하는 위험 신호를 안내합니다.",
    importantNotice: "고열, 심한 통증, 호흡곤란, 심한 출혈이 있으면 지체 없이 응급실을 방문하세요.",
    contact: "응급 상황 시 119, 응급실 문의 대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c40",
    slug: "discharge-medication-pickup",
    title: "퇴원약 수령 안내",
    category: "퇴원",
    subcategory: "퇴원약 수령",
    departments: ["원무팀"],
    patientStages: ["before-discharge"],
    summary: "퇴원 시 처방약을 수령하는 절차와 위치를 안내합니다.",
    location: "본관 1층 외래약국",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c41",
    slug: "wound-care-after-discharge",
    title: "퇴원 후 상처 소독 관리 안내",
    category: "퇴원",
    subcategory: "퇴원 후 상처 소독 관리 안내",
    departments: ["외과", "정형외과"],
    patientStages: ["after-discharge"],
    summary: "퇴원 후 가정에서의 상처 소독 및 관리 방법을 안내합니다.",
    after: "손을 깨끗이 씻은 후 처방받은 소독법에 따라 관리해주세요.",
    importantNotice: "진물, 발적, 열감이 심해지면 즉시 병원에 방문하세요.",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: true,
    version: 1,
    lastUpdated: "2026-06-10",
  },
  {
    contentId: "c42",
    slug: "discharge-billing",
    title: "퇴원 수속 및 비용 정산 안내",
    category: "퇴원",
    subcategory: "퇴원 수속 및 비용정산",
    departments: ["원무팀"],
    patientStages: ["before-discharge"],
    summary: "퇴원 시 진료비 정산 절차와 결제 방법을 안내합니다.",
    location: "본관 3층 원무팀 퇴원 창구",
    contact: "원무팀 퇴원계 02-2290-9076~7",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-06-10",
  },

  // ───────────────────── 기타 (8) ─────────────────────
  {
    contentId: "c43",
    slug: "find-test-room",
    title: "검사실 찾아가기",
    category: "기타",
    subcategory: "검사실 찾아가기",
    departments: ["전과공통"],
    patientStages: [],
    summary: "동·층별 주요 검사실 위치를 안내합니다.",
    location: "본관 2~3층(영상의학과·핵의학과), 서관 6층(내시경센터)",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c44",
    slug: "find-clinic-room",
    title: "진료실 찾아가기",
    category: "기타",
    subcategory: "진료실 찾아가기",
    departments: ["전과공통"],
    patientStages: [],
    summary: "동·층별 진료과 위치를 안내합니다.",
    location: "본관 각 층 안내도 참고",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c45",
    slug: "registration-payment",
    title: "원무팀 접수·수납 안내",
    category: "기타",
    subcategory: "원무팀 접수, 수납 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "외래 접수와 수납 절차, 무인수납기 이용 방법을 안내합니다.",
    location: "본관 1층 고객서비스센터, 각 층 수납창구",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c46",
    slug: "guardian-guide",
    title: "보호자 안내",
    category: "기타",
    subcategory: "보호자 안내",
    departments: ["전과공통"],
    patientStages: [],
    summary: "검사·수술 시 보호자 동행 및 대기 안내입니다.",
    location: "각 검사실·수술실 보호자 대기공간",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c47",
    slug: "medical-records",
    title: "의무기록 발급 및 제증명 서류 안내",
    category: "기타",
    subcategory: "의무기록 발급 및 제증명 서류 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "진단서, 소견서 등 제증명 서류 발급 절차와 소요 시간을 안내합니다.",
    location: "본관 3층 원무팀 (무인 제증명 발급기)",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c48",
    slug: "parking-transit",
    title: "주차 및 대중교통 이용 안내",
    category: "기타",
    subcategory: "주차 및 대중교통 이용 안내",
    departments: ["전과공통"],
    patientStages: [],
    summary: "병원 주차장 이용 방법과 대중교통 경로를 안내합니다.",
    location: "본관·동관·타워주차장",
    contact: "주차 문의 02-2290-8557",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c49",
    slug: "non-covered-costs",
    title: "비급여 진료비용 및 실손보험 안내",
    category: "기타",
    subcategory: "비급여 진료비용 및 실손보험 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "비급여 항목의 비용 안내와 실손보험 서류 준비 방법을 안내합니다.",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 2,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
  {
    contentId: "c50",
    slug: "referral-center",
    title: "진료협력센터(타 병원 의뢰) 안내",
    category: "기타",
    subcategory: "진료협력센터(타 병원 의뢰) 안내",
    departments: ["원무팀"],
    patientStages: [],
    summary: "타 병원 진료 의뢰서 발급과 진료협력센터 이용 방법을 안내합니다.",
    location: "본관 1층 진료협력센터",
    contact: "대표전화 02-2290-8114",
    estimatedReadMinutes: 1,
    status: "게시",
    needsClinicalReview: false,
    version: 1,
    lastUpdated: "2026-05-20",
  },
];

export function findGuideBySlug(slug: string): GuideContent | undefined {
  return GUIDES.find((g) => g.slug === slug);
}
